In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("IPLytics Started Successfully")

IPLytics Started Successfully

In [7]:
rcb_2025_matches = pd.DataFrame({

    "date": [
        "2025-03-22",
        "2025-03-28",
        "2025-04-02",
        "2025-04-07",
        "2025-04-10",
        "2025-04-13",
        "2025-04-18",
        "2025-04-20",
        "2025-04-24",
        "2025-04-27",
        "2025-05-03",
        "2025-05-23",
        "2025-05-27",
        "2025-05-29",
        "2025-06-03"
    ],

    "opponent": [
        "KKR",
        "CSK",
        "GT",
        "MI",
        "DC",
        "RR",
        "PBKS",
        "PBKS",
        "RR",
        "DC",
        "CSK",
        "SRH",
        "LSG",
        "PBKS",
        "PBKS"
    ],

    "venue": [
        "Kolkata",
        "Chennai",
        "Bengaluru",
        "Mumbai",
        "Bengaluru",
        "Jaipur",
        "Bengaluru",
        "Mullanpur",
        "Bengaluru",
        "Delhi",
        "Bengaluru",
        "Lucknow",
        "Lucknow",
        "Mullanpur",
        "Ahmedabad"
    ],

    "rcb_score": [
        177,
        196,
        169,
        221,
        163,
        175,
        95,
        159,
        205,
        165,
        213,
        189,
        230,
        106,
        190
    ],

    "opponent_score": [
        174,
        146,
        170,
        209,
        169,
        173,
        98,
        157,
        194,
        162,
        211,
        231,
        227,
        101,
        184
    ],

    "result": [
        "Win",
        "Win",
        "Loss",
        "Win",
        "Loss",
        "Win",
        "Loss",
        "Win",
        "Win",
        "Win",
        "Win",
        "Loss",
        "Win",
        "Win",
        "Win"
    ]
})

rcb_2025_matches

          date opponent      venue  rcb_score  opponent_score result
0   2025-03-22      KKR    Kolkata        177             174    Win
1   2025-03-28      CSK    Chennai        196             146    Win
2   2025-04-02       GT  Bengaluru        169             170   Loss
3   2025-04-07       MI     Mumbai        221             209    Win
4   2025-04-10       DC  Bengaluru        163             169   Loss
5   2025-04-13       RR     Jaipur        175             173    Win
6   2025-04-18     PBKS  Bengaluru         95              98   Loss
7   2025-04-20     PBKS  Mullanpur        159             157    Win
8   2025-04-24       RR  Bengaluru        205             194    Win
9   2025-04-27       DC      Delhi        165             162    Win
10  2025-05-03      CSK  Bengaluru        213             211    Win
11  2025-05-23      SRH    Lucknow        189             231   Loss
12  2025-05-27      LSG    Lucknow        230             227    Win
13  2025-05-29     PBKS  Mullanpur        106             101    Win
14  2025-06-03     PBKS  Ahmedabad        190             184    Win

In [10]:
rcb_2025_matches.to_csv(
    "../data/processed/rcb_2025_matches.csv",
    index=False
)
print("RCB 2025 Dataset Saved Successfully")

RCB 2025 Dataset Saved Successfully

In [9]:
saved_data = pd.read_csv(
    "../data/processed/rcb_2025_matches.csv"
)
saved_data.head()

         date opponent      venue  rcb_score  opponent_score result
0  2025-03-22      KKR    Kolkata        177             174    Win
1  2025-03-28      CSK    Chennai        196             146    Win
2  2025-04-02       GT  Bengaluru        169             170   Loss
3  2025-04-07       MI     Mumbai        221             209    Win
4  2025-04-10       DC  Bengaluru        163             169   Loss

In [11]:
rcb_2026_matches = pd.DataFrame({

    "date": [
        "2026-03-28",
        "2026-04-05",
        "2026-04-10",
        "2026-04-12",
        "2026-04-15",
        "2026-04-18",
        "2026-04-24",
        "2026-04-27",
        "2026-04-30",
        "2026-05-07",
        "2026-05-10",
        "2026-05-13",
        "2026-05-17",
        "2026-05-22",
        "2026-05-26"
    ],

    "opponent": [
        "SRH",
        "CSK",
        "RR",
        "MI",
        "LSG",
        "DC",
        "GT",
        "DC",
        "GT",
        "LSG",
        "MI",
        "KKR",
        "PBKS",
        "SRH",
        "GT"
    ],

    "venue": [
        "Bengaluru",
        "Bengaluru",
        "Guwahati",
        "Mumbai",
        "Bengaluru",
        "Bengaluru",
        "Bengaluru",
        "Delhi",
        "Ahmedabad",
        "Lucknow",
        "Raipur",
        "Raipur",
        "Dharamsala",
        "Hyderabad",
        "Dharamsala"
    ],

    "rcb_score": [
        203,
        250,
        201,
        240,
        149,
        175,
        206,
        77,
        155,
        203,
        167,
        194,
        222,
        200,
        254
    ],

    "opponent_score": [
        201,
        207,
        202,
        222,
        146,
        179,
        205,
        75,
        158,
        209,
        166,
        192,
        199,
        255,
        162
    ],

    "result": [
        "Win",
        "Win",
        "Loss",
        "Win",
        "Win",
        "Loss",
        "Win",
        "Win",
        "Loss",
        "Loss",
        "Win",
        "Win",
        "Win",
        "Loss",
        "Win"
    ]
})

rcb_2026_matches

          date opponent       venue  rcb_score  opponent_score result
0   2026-03-28      SRH   Bengaluru        203             201    Win
1   2026-04-05      CSK   Bengaluru        250             207    Win
2   2026-04-10       RR    Guwahati        201             202   Loss
3   2026-04-12       MI      Mumbai        240             222    Win
4   2026-04-15      LSG   Bengaluru        149             146    Win
5   2026-04-18       DC   Bengaluru        175             179   Loss
6   2026-04-24       GT   Bengaluru        206             205    Win
7   2026-04-27       DC       Delhi         77              75    Win
8   2026-04-30       GT   Ahmedabad        155             158   Loss
9   2026-05-07      LSG     Lucknow        203             209   Loss
10  2026-05-10       MI      Raipur        167             166    Win
11  2026-05-13      KKR      Raipur        194             192    Win
12  2026-05-17     PBKS  Dharamsala        222             199    Win
13  2026-05-22      SRH   Hyderabad        200             255   Loss
14  2026-05-26       GT  Dharamsala        254             162    Win

In [12]:
rcb_2026_matches.to_csv("../data/processed/rcb_2026_matches.csv", index=False)

print("RCB 2026 Dataset Saved Successfully")

RCB 2026 Dataset Saved Successfully

In [14]:
saved_data = pd.read_csv(
    "../data/processed/rcb_2026_matches.csv"
)
saved_data.head()

         date opponent      venue  rcb_score  opponent_score result
0  2026-03-28      SRH  Bengaluru        203             201    Win
1  2026-04-05      CSK  Bengaluru        250             207    Win
2  2026-04-10       RR   Guwahati        201             202   Loss
3  2026-04-12       MI     Mumbai        240             222    Win
4  2026-04-15      LSG  Bengaluru        149             146    Win

In [15]:
rcb_2025_matches["season"] = 2025
rcb_2026_matches["season"] = 2026

combined_rcb = pd.concat([
    rcb_2025_matches,
    rcb_2026_matches
])

combined_rcb

          date opponent       venue  rcb_score  opponent_score result  season
0   2025-03-22      KKR     Kolkata        177             174    Win    2025
1   2025-03-28      CSK     Chennai        196             146    Win    2025
2   2025-04-02       GT   Bengaluru        169             170   Loss    2025
3   2025-04-07       MI      Mumbai        221             209    Win    2025
4   2025-04-10       DC   Bengaluru        163             169   Loss    2025
5   2025-04-13       RR      Jaipur        175             173    Win    2025
6   2025-04-18     PBKS   Bengaluru         95              98   Loss    2025
7   2025-04-20     PBKS   Mullanpur        159             157    Win    2025
8   2025-04-24       RR   Bengaluru        205             194    Win    2025
9   2025-04-27       DC       Delhi        165             162    Win    2025
10  2025-05-03      CSK   Bengaluru        213             211    Win    2025
11  2025-05-23      SRH     Lucknow        189             231   Loss    2025
12  2025-05-27      LSG     Lucknow        230             227    Win    2025
13  2025-05-29     PBKS   Mullanpur        106             101    Win    2025
14  2025-06-03     PBKS   Ahmedabad        190             184    Win    2025
0   2026-03-28      SRH   Bengaluru        203             201    Win    2026
1   2026-04-05      CSK   Bengaluru        250             207    Win    2026
2   2026-04-10       RR    Guwahati        201             202   Loss    2026
3   2026-04-12       MI      Mumbai        240             222    Win    2026
4   2026-04-15      LSG   Bengaluru        149             146    Win    2026
5   2026-04-18       DC   Bengaluru        175             179   Loss    2026
6   2026-04-24       GT   Bengaluru        206             205    Win    2026
7   2026-04-27       DC       Delhi         77              75    Win    2026
8   2026-04-30       GT   Ahmedabad        155             158   Loss    2026
9   2026-05-07      LSG     Lucknow        203             209   Loss    2026
10  2026-05-10       MI      Raipur        167             166    Win    2026
11  2026-05-13      KKR      Raipur        194             192    Win    2026
12  2026-05-17     PBKS  Dharamsala        222             199    Win    2026
13  2026-05-22      SRH   Hyderabad        200             255   Loss    2026
14  2026-05-26       GT  Dharamsala        254             162    Win    2026

In [16]:
combined_rcb.to_csv(
    "../data/processed/combined_rcb_dataset.csv",
    index=False
)
print("Combined Dataset Saved Successfully")

Combined Dataset Saved Successfully

In [17]:
# OVER 2

over_2_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [2] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Ravichandran Ashwin"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Phil Salt",
        "Phil Salt"
    ],

    "runs": [
        6,4,1,0,1,4
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 3

over_3_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [3] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Khaleel Ahmed"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Phil Salt",
        "Phil Salt",
        "Phil Salt"
    ],

    "runs": [
        0,0,0,4,0,2
    ],

    "extra": [
        0,0,1,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 4

over_4_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [4] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Sam Curran"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Phil Salt",
        "Phil Salt",
        "Phil Salt"
    ],

    "runs": [
        0,2,0,0,1,1
    ],

    "extra": [
        0,0,0,1,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 5

over_5_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [5] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Noor Ahmad"
    ] * 7,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Phil Salt",
        "Phil Salt",
        "Phil Salt"
    ],

    "runs": [
        1,0,1,0,4,1,0
    ],

    "extra": [
        0,1,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0,1
    ]
})



# OVER 6

over_6_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [6] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Sam Curran"
    ] * 7,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Devdutt Padikkal",
        "Devdutt Padikkal",
        "Devdutt Padikkal"
    ],

    "runs": [
        1,0,2,0,6,0,1
    ],

    "extra": [
        0,0,0,0,0,1,0
    ],

    "wicket": [
        0,0,0,0,0,0,0
    ]
})



# OVER 7

over_7_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [7] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Ravindra Jadeja"
    ] * 6,

    "batter": [
        "Devdutt Padikkal"
    ] * 6,

    "runs": [
        0,4,0,4,6,1
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 8

over_8_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [8] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Ravichandran Ashwin"
    ] * 7,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Devdutt Padikkal",
        "Devdutt Padikkal",
        "Devdutt Padikkal",
        "Devdutt Padikkal",
        "Rajat Patidar"
    ],

    "runs": [
        0,1,0,1,2,0,1
    ],

    "extra": [
        1,0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,1,0
    ]
})



# OVER 9

over_9_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [9] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Matheesha Pathirana"
    ] * 7,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        0,0,1,1,0,1,1
    ],

    "extra": [
        1,0,0,0,1,0,0
    ],

    "wicket": [
        0,0,0,0,0,0,0
    ]
})



# OVER 10

over_10_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [10] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Noor Ahmad"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        1,1,1,1,0,6
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 11

over_11_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [11] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Matheesha Pathirana"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Virat Kohli",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        0,6,4,1,4,1
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 12

over_12_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [12] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Ravindra Jadeja"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        1,1,1,2,1,1
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 13

over_13_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [13] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Noor Ahmad"
    ] * 6,

    "batter": [
        "Virat Kohli",
        "Virat Kohli",
        "Liam Livingstone",
        "Liam Livingstone",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        1,0,0,1,0,1
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,1,0,0,0,0
    ]
})



# OVER 14

over_14_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [14] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Ravindra Jadeja"
    ] * 7,

    "batter": [
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        6,4,0,4,0,0,0
    ],

    "extra": [
        0,0,0,0,0,1,0
    ],

    "wicket": [
        0,0,0,0,0,0,0
    ]
})



# OVER 15

over_15_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [15] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Khaleel Ahmed"
    ] * 6,

    "batter": [
        "Liam Livingstone",
        "Liam Livingstone",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        0,1,1,0,2,0
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,0,0,0
    ]
})



# OVER 16

over_16_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [16] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Noor Ahmad"
    ] * 6,

    "batter": [
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Liam Livingstone",
        "Rajat Patidar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        1,6,0,1,1,6
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,1,0,0,0
    ]
})



# OVER 17

over_17_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [17] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Matheesha Pathirana"
    ] * 7,

    "batter": [
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        1,1,6,0,0,1,4
    ],

    "extra": [
        0,0,0,0,1,0,0
    ],

    "wicket": [
        0,0,0,0,0,0,0
    ]
})



# OVER 18

over_18_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 6,

    "innings": [1] * 6,

    "over": [18] * 6,

    "ball": [1,2,3,4,5,6],

    "bowler": [
        "Khaleel Ahmed"
    ] * 6,

    "batter": [
        "Tim David",
        "Tim David",
        "Jitesh Sharma",
        "Jitesh Sharma",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        4,1,0,0,4,0
    ],

    "extra": [
        0,0,0,0,0,0
    ],

    "wicket": [
        0,0,0,1,0,0
    ]
})



# OVER 19

over_19_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [19] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Matheesha Pathirana"
    ] * 7,

    "batter": [
        "Krunal Pandya",
        "Krunal Pandya",
        "Bhuvneshwar Kumar",
        "Bhuvneshwar Kumar",
        "Bhuvneshwar Kumar",
        "Rajat Patidar",
        "Rajat Patidar"
    ],

    "runs": [
        0,0,0,0,0,0,1
    ],

    "extra": [
        0,0,0,1,0,0,0
    ],

    "wicket": [
        1,0,0,0,1,0,0
    ]
})



# OVER 20

over_20_data = pd.DataFrame({

    "match": ["RCB vs CSK"] * 7,

    "innings": [1] * 7,

    "over": [20] * 7,

    "ball": [1,2,3,4,5,6,7],

    "bowler": [
        "Sam Curran"
    ] * 7,

    "batter": [
        "Tim David",
        "Tim David",
        "Tim David",
        "Tim David",
        "Tim David",
        "Tim David",
        "Tim David"
    ],

    "runs": [
        0,0,6,6,6,0,0
    ],

    "extra": [
        0,0,0,0,0,1,0
    ],

    "wicket": [
        0,0,0,0,0,0,0
    ]
})



# COMBINE ALL OVERS

rcb_vs_csk_2025 = pd.concat([
    rcb_vs_csk_2025,
    over_2_data,
    over_3_data,
    over_4_data,
    over_5_data,
    over_6_data,
    over_7_data,
    over_8_data,
    over_9_data,
    over_10_data,
    over_11_data,
    over_12_data,
    over_13_data,
    over_14_data,
    over_15_data,
    over_16_data,
    over_17_data,
    over_18_data,
    over_19_data,
    over_20_data
])

rcb_vs_csk_2025

NameError: name 'rcb_vs_csk_2025' is not defined